<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\msl_marker.png" />
    <None Remove="Resources\target.png" />
    <None Remove="Resources\tgt_marker.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="GMap.NET.Core" Version="2.1.7" />
    <PackageReference Include="GMap.NET.WinPresentation" Version="2.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Driver\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\msl_marker.png" />
    <Resource Include="Resources\target.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\tgt_marker.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\network.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
