<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Models\**" />
    <None Remove="Services\**" />
    <Page Remove="Models\**" />
    <Page Remove="Services\**" />
  </ItemGroup>

</Project>
